apiVersion: apps/v1
kind: Deployment
metadata:
  name: ase-deployment
  labels:
    app: ase
spec:
  selector:
    matchLabels:
      app: ase
  replicas: 1
  template:
    metadata:
      labels:
        app: ase
    spec:
      containers:
      - name: ase
        image: gitlab.lrz.de:5005/ase-22-23/team15/tum-atse-proj/frontend:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
