.login-cr:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

build-job:
  stage: build
  extends: .login-cr
  script:
    - docker build -t $CI_REGISTRY/ase-22-23/team15/tum-atse-proj/frontend:latest frontend
    - docker push $CI_REGISTRY/ase-22-23/team15/tum-atse-proj/frontend:latest
