variables:
  PROD_USER: ase
  PROD_HOST: tum-ase.westeurope.cloudapp.azure.com
  CI_REPO: $CI_REGISTRY/ase-22-23/team15/tum-atse-proj

.login-cr:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

.login-prod:
  before_script:
    - eval "$(ssh-agent -s)"
    - echo "$SSH_PRIVATE_KEY_PROD" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

build-job:
  stage: build
  extends: .login-cr
  script:
    - docker build -t $CI_REPO/frontend:latest frontend
    - docker push $CI_REPO/frontend:latest

deploy-job:
  stage: deploy
  extends: .login-prod
  script:
    - scp docker-compose.prod.yml $PROD_USER@$PROD_HOST:/deployments/prod/docker-compose.yml
    - |
      ssh $PROD_USER@$PROD_HOST "
        cd /deployments/prod;
        docker-compose pull;
        docker-compose down --remove-orphans;
        docker-compose up -d;
        sudo echo \"<!DOCTYPE html><html><head></head><body>Last updated: $(date --utc +'%Y-%m-%d %T') UTC</body></html>\" > /var/www/html/info.html;
      "
