variables:
  CI_REPO: $CI_REGISTRY/ase-22-23/team15/tum-ase-proj

## Login to Container Registry
.login-cr:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

## Login to deployment environment via SSH
.login-deploy:
  before_script:
    - eval "$(ssh-agent -s)"
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

## Build images and push to CR
build-router:
  stage: build
  extends: .login-cr
  script:
    - docker build -t $CI_REPO/router:$CI_COMMIT_SHA router
    - docker push $CI_REPO/router:$CI_COMMIT_SHA

build-frontend:
  stage: build
  extends: .login-cr
  script:
    - docker build -t $CI_REPO/frontend:$CI_COMMIT_SHA frontend
    - docker push $CI_REPO/frontend:$CI_COMMIT_SHA

build-backend:
  stage: build
  extends: .login-cr
  script:
    - cd backend
    - chmod 755 gradlew
    - ./gradlew build
    - cd ..
    - docker build -t $CI_REPO/backend:$CI_COMMIT_SHA backend
    - docker push $CI_REPO/backend:$CI_COMMIT_SHA

## Deploy
.deploy:
  stage: deploy
  extends: .login-deploy
  script:
    - scp docker-compose.prod.yml $USER@$HOST:$DEPLOYMENT_PATH/docker-compose.yml
    - |
      ssh $USER@$HOST "
        cd $DEPLOYMENT_PATH &&
        rm .env &&
        echo "TAG=$CI_COMMIT_SHA" >> .env &&
        cat .env.prod >> .env &&
        docker-compose pull &&
        docker-compose down --remove-orphans &&
        docker-compose up -d &&
        echo \"Last updated: $(date --utc +'%Y-%m-%d %T') UTC<br>Commit SHA: $CI_COMMIT_SHA\" | sudo tee /var/www/html/info.html
      "

## Deploy to staging
deploy-stag:
  stage: deploy
  when: manual
  extends: .deploy
  variables:
    SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY_STAG
    USER: ase
    HOST: tum-ase.westeurope.cloudapp.azure.com
    DEPLOYMENT_PATH: /deployments/stag
  script:
    - !reference [.deploy, script]

## Deploy to production
deploy-prod:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  extends: .deploy
  variables:
    SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY_PROD
    USER: ase
    HOST: tum-ase.westeurope.cloudapp.azure.com
    DEPLOYMENT_PATH: /deployments/prod
  script:
    - !reference [.deploy, script]
