variables:
  PROD_USER: ase
  PROD_HOST: tum-ase.westeurope.cloudapp.azure.com
  PROD_DEPLOYMENT_PATH: /deployments/prod
  CI_REPO: $CI_REGISTRY/ase-22-23/team15/tum-ase-proj

## Login to Container Registry
.login-cr:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

## Login to production environment via SSH
.login-prod:
  before_script:
    - eval "$(ssh-agent -s)"
    - echo "$SSH_PRIVATE_KEY_PROD" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

## Build image and push it to CR
build-job:
  stage: build
  extends: .login-cr
  script:
    - docker build -t $CI_REPO/frontend:$CI_COMMIT_SHA frontend
    - docker push $CI_REPO/frontend:$CI_COMMIT_SHA

## Deploy
.deploy:
  stage: deploy
  extends: .login-prod
  script:
    - scp docker-compose.prod.yml $USER@$HOST:$DEPLOYMENT_PATH/docker-compose.yml
    - |
      ssh $USER@$HOST "
        cd $DEPLOYMENT_PATH;
        rm .env
        echo "TAG=$CI_COMMIT_SHA" >> .env
        cat .env.prod >> .env
        docker-compose pull;
        docker-compose down --remove-orphans;
        docker-compose up -d;
        echo \"Last updated: $(date --utc +'%Y-%m-%d %T') UTC<br>Commit SHA: $CI_COMMIT_SHA\" | sudo tee /var/www/html/info.html;
      "

## Deploy to production
deploy-prod:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  extends: .login-prod
  variables:
    USER: $PROD_USER
    HOST: $PROD_HOST
    DEPLOYMENT_PATH: $PROD_DEPLOYMENT_PATH
