variables:
  DEPLOY_USER: ase
  DEPLOY_HOST: tum-ase.westeurope.cloudapp.azure.com
  CI_REPO: $CI_REGISTRY/ase-22-23/team15/tum-atse-proj

.login-cr:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

.login-env-deployment:
  before_script:
    - eval "$(ssh-agent -s)"
    - ssh-add $SSH_PRIVATE_KEY_DEPLOY

build-job:
  stage: build
  extends: .login-cr
  script:
    - docker build -t $CI_REPO/frontend:latest frontend
    - docker push $CI_REPO/frontend:latest

deploy-job:
  stage: deploy
  extends: .login-env-deployment
  script:
    - scp docker-compose.prod.yml $DEPLOY_USER@$DEPLOY_HOST:~/docker-compose.yml
    - ssh $DEPLOY_USER@$DEPLOY_HOST "sudo mv -f ~/docker-compose.yml /deployments/prod/docker-compose.yml"
