version: "3.9"

services:
  api-gateway:
    container_name: api-gateway
    image: gitlab.lrz.de:5005/ase-22-23/team15/tum-ase-proj/api-gateway:${TAG}
    depends_on:
      service-registry:
        condition: service_healthy
    environment:
      PORT: 10789
    ports:
      - ${ROUTER_PORT}:10789

  service-registry:
    container_name: service-registry
    image: gitlab.lrz.de:5005/ase-22-23/team15/tum-ase-proj/service-registry:${TAG}
    healthcheck:
      test: curl localhost:8761
      start_period: 10s
      interval: 1s
      timeout: 1s
      retries: 50
    environment:
      PORT: 8761

  frontend:
    image: gitlab.lrz.de:5005/ase-22-23/team15/tum-ase-proj/frontend:${TAG}

  delivery:
    image: gitlab.lrz.de:5005/ase-22-23/team15/tum-ase-proj/delivery:${TAG}
    depends_on:
      db:
        condition: service_healthy
      service-registry:
        condition: service_healthy
    environment:
      FRONTEND_ADDRESS: http://www.coolwebsite.com
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_ADDRESS: asedelivery.t15@gmail.com
      EMAIL_USERNAME: asedelivery.t15@gmail.com
      EMAIL_PASSWORD: ${BACKEND_EMAIL_PASSWORD}

  auth:
    image: gitlab.lrz.de:5005/ase-22-23/team15/tum-ase-proj/auth:${TAG}
    depends_on:
      db:
        condition: service_healthy
      service-registry:
        condition: service_healthy
    environment:
      FRONTEND_ADDRESS: http://www.coolwebsite.com
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  db:
    container_name: db
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: asedelivery
    healthcheck:
      test: test -f healthcheck.txt || (echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet && touch healthcheck.txt)
      start_period: 5s
      interval: 1s
      timeout: 1s
      retries: 50
    volumes:
      - data/mongo/data/db:/data/db

  db-admin:
    image: mongo-express:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://root:${MONGO_INITDB_ROOT_PASSWORD}@db:27017/
