version: "3.9"

services:
  router:
    build: router
    ports:
      - 8000:80

  frontend:
    build: frontend
    ports:
      - 8001:80

  db:
    image: mongo:6.0
    ports:
      - 8003:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  db-admin:
    image: mongo-express:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8004:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@db:27017/

  backend:
    build: backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8002:80
    environment:
      ADMIN_PASSWORD: 1234
    volumes:
      - ./backend:/app
    command: "/run.dev.sh"
