version: "3.9"

services:
  router:
    build: router
    ports:
      - 8000:80

  frontend:
    build: frontend
    ports:
      - 8001:3000

  db:
    image: mongo:6.0
    ports:
      - 8003:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    healthcheck:
      test: test -f healthcheck.txt || (echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet && touch healthcheck.txt)
      interval: 10s
      timeout: 10s
      retries: 5
    logging:
      driver: none

  db-admin:
    image: mongo-express:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8004:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@db:27017/
    logging:
      driver: none


  backend:
    build: backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8002:80
    environment:
      BACKEND_ADMIN_PASSWORD: 1234
      FRONTEND_ADDRESS: http://localhost
      MONGO_INITDB_ROOT_PASSWORD: password
      EMAIL_HOST: mailhog
      EMAIL_PORT: 1025
      EMAIL_ADDRESS: asedelivery@mailhog.com
      EMAIL_USERNAME: user123
      EMAIL_PASSWORD: 1234
    volumes:
      - ./backend:/app
    command: "/run.dev.sh"

  mailhog:
    build: mailhog
    ports:
      - 8025:8025
    logging:
      driver: none
