version: "3.9"

services:
  router:
    image: gitlab.lrz.de:5005/ase-22-23/team15/tum-ase-proj/router:${TAG}
    ports:
      - ${ROUTER_PORT}:80

  frontend:
    image: gitlab.lrz.de:5005/ase-22-23/team15/tum-ase-proj/frontend:${TAG}

  db:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    healthcheck:
      test: test -f healthcheck.txt || (echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet && touch healthcheck.txt)
      interval: 10s
      timeout: 10s
      retries: 5

  db-admin:
    image: mongo-express:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://root:${ME_CONFIG_MONGODB_ADMINPASSWORD}@db:27017/

  backend:
    image: gitlab.lrz.de:5005/ase-22-23/team15/tum-ase-proj/backend:${TAG}
    environment:
      ADMIN_PASSWORD: ${BACKEND_ADMIN_PASSWORD}
      FRONTEND_ADDRESS: http://www.coolwebsite.com
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_ADDRESS: asedelivery.t15@gmail.com
      EMAIL_USERNAME: asedelivery.t15@gmail.com
      EMAIL_PASSWORD: ${BACKEND_EMAIL_PASSWORD}
