server:
  port: 80

frontend:
  address: ${FRONTEND_ADDRESS}

spring:
  data:
    mongodb:
      host: db
      authentication-database: admin
      database: asedelivery
      username: root
      password: ${MONGO_INITDB_ROOT_PASSWORD}

  mail:
    protocol: smtp
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    from: ${EMAIL_ADDRESS}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

